/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Jihambru (https://sketchfab.com/jihambru)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ethereum-logo-3d-3b8be89e01514b48bd7a4e52582f6d50
Title: Ethereum logo 3D
*/

import eth from '../src/assets/3DModels/ethereum_logo_3d/scene.gltf'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

gsap.registerPlugin(useGSAP)

export function EthereumLogo(props) {
  const ethRef = useRef()

  useGSAP(() => {
    gsap.from(ethRef.current.position, {
      x: 6,
      duration: 2.5,
      ease: 'power3.out'
    })
  })


  const { nodes, materials } = useGLTF(eth)
  
  return (
    <group ref={ethRef} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.549}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="E_th_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.SILVER_metal} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(eth)
